language: python
python:
    - "3.6"
services:
    - postgresql: "9.6"
before_script:
    - psql -c "CREATE ROLE paneity_usr WITH createdb password 'password';" -U postgres
install: "pip install -r requirements.txt"
script: "python manage.py test"
