language: python
python:
    - "3.6"
services:
    - postgresql: "9.6"
before_script:
    - psql -c "CREATE ROLE paneity_usr WITH LOGIN PASSWORD 'password' CREATEDB;" -U postgres
    - psql -c "CREATE DATABASE paneity_dev WITH OWNER paneity_usr;" -U postgres
    - cd .. && git clone https://github.com/reed-college/Spirit.git && rm Spirit/.travis.yml && cd paneity 
    - python manage.py migrate
install: "pip install -r requirements.txt"
script: 
    - "python manage.py test tutor"
    - "python manage.py loaddata subjects courses users questions chats"
